/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Clases.SolucionRecursiva;

/**
 *
 * @author wsulivan
 */
public class GUI_Demostracion extends javax.swing.JFrame {
    /**
     * Creates new form GUI_PanelJuego
     */
    public GUI_Demostracion() {
        initComponents();
        setLocationRelativeTo(null);
        //GUI_Demostracion.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Movimientos = new javax.swing.JTextArea();
        label2 = new java.awt.Label();
        btn_Limpiar = new java.awt.Button();
        btn_Salir = new java.awt.Button();
        label3 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_modoFacil = new javax.swing.JMenuItem();
        jMenuItem_modoMedio = new javax.swing.JMenuItem();
        jMenuItem_modoDificil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demostracion del Juego");

        jTextArea_Movimientos.setBackground(java.awt.SystemColor.controlHighlight);
        jTextArea_Movimientos.setColumns(20);
        jTextArea_Movimientos.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Movimientos);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setEnabled(false);
        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Solucion del Problema");

        btn_Limpiar.setBackground(java.awt.SystemColor.textHighlight);
        btn_Limpiar.setLabel("Limpiar Datos");
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });

        btn_Salir.setBackground(java.awt.SystemColor.textHighlight);
        btn_Salir.setLabel("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        label3.setEnabled(false);
        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setText("Movimientos");

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Opciones");

        jMenuItem3.setText("Salir");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Niveles");

        jMenuItem_modoFacil.setText("3 Discos");
        jMenuItem_modoFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_modoFacilActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_modoFacil);

        jMenuItem_modoMedio.setText("6 Discos");
        jMenuItem_modoMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_modoMedioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_modoMedio);

        jMenuItem_modoDificil.setText("8 Discos");
        jMenuItem_modoDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_modoDificilActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_modoDificil);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_modoFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_modoFacilActionPerformed
        // TODO add your handling code here:
        modoFacil();
    }//GEN-LAST:event_jMenuItem_modoFacilActionPerformed

    private void jMenuItem_modoMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_modoMedioActionPerformed
        // TODO add your handling code here:
        modoMedio();
    }//GEN-LAST:event_jMenuItem_modoMedioActionPerformed

    private void jMenuItem_modoDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_modoDificilActionPerformed
        // TODO add your handling code here:
        modoDificill();
    }//GEN-LAST:event_jMenuItem_modoDificilActionPerformed

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        jTextArea_Movimientos.setText(null);
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Demostracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Demostracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Demostracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Demostracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Demostracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_Limpiar;
    private java.awt.Button btn_Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem_modoDificil;
    private javax.swing.JMenuItem jMenuItem_modoFacil;
    private javax.swing.JMenuItem jMenuItem_modoMedio;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_Movimientos;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void modoFacil(){
        SolucionRecursiva objetoSolucion=new SolucionRecursiva();
        int numeroDiscos=3;
        objetoSolucion.solicitaDatos(numeroDiscos);        
        String men=objetoSolucion.concatenaImpresion();        
        jTextArea_Movimientos.setText(men);
    }    

    /**
     *
     */
    public void modoMedio(){
        SolucionRecursiva objetoSolucion=new SolucionRecursiva();
        int numeroDiscos=6;
        objetoSolucion.solicitaDatos(numeroDiscos);
        String men=objetoSolucion.concatenaImpresion();        
        jTextArea_Movimientos.setText(men);
    }    

    /**
     *
     */
    public void modoDificill(){
        SolucionRecursiva objetoSolucion=new SolucionRecursiva();
        int numeroDiscos=8;
        objetoSolucion.solicitaDatos(numeroDiscos);
        String men=objetoSolucion.concatenaImpresion();        
        jTextArea_Movimientos.setText(men);
    }
}
